In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("homeprices.csv")
df.head()

              town  area   price
0  monroe township  2600  550000
1  monroe township  3000  565000
2  monroe township  3200  610000
3  monroe township  3600  680000
4  monroe township  4000  725000

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   town    13 non-null     str
 1   area    13 non-null     int64
 2   price   13 non-null     int64
dtypes: int64(2), str(1)
memory usage: 444.0 bytes

In [5]:
dummies = pd.get_dummies(df.town)
dummies

    monroe township  robinsville  west windsor
0              True        False         False
1              True        False         False
2              True        False         False
3              True        False         False
4              True        False         False
5             False        False          True
6             False        False          True
7             False        False          True
8             False        False          True
9             False         True         False
10            False         True         False
11            False         True         False
12            False         True         False

In [7]:
df_dummies = pd.concat([df,dummies],axis='columns')
df_dummies

               town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000             True        False         False
1   monroe township  3000  565000             True        False         False
2   monroe township  3200  610000             True        False         False
3   monroe township  3600  680000             True        False         False
4   monroe township  4000  725000             True        False         False
5      west windsor  2600  585000            False        False          True
6      west windsor  2800  615000            False        False          True
7      west windsor  3300  650000            False        False          True
8      west windsor  3600  710000            False        False          True
9       robinsville  2600  575000            False         True         False
10      robinsville  2900  600000            False         True         False
11      robinsville  3100  620000            False         True         False
12      robinsville  3600  695000            False         True         False

In [9]:
df_dummies.drop(['town','west windsor'],axis='columns',inplace=True)
df_dummies

    area   price  monroe township  robinsville
0   2600  550000             True        False
1   3000  565000             True        False
2   3200  610000             True        False
3   3600  680000             True        False
4   4000  725000             True        False
5   2600  585000            False        False
6   2800  615000            False        False
7   3300  650000            False        False
8   3600  710000            False        False
9   2600  575000            False         True
10  2900  600000            False         True
11  3100  620000            False         True
12  3600  695000            False         True

In [10]:
X = df_dummies.drop(['price'],axis='columns')
X

    area  monroe township  robinsville
0   2600             True        False
1   3000             True        False
2   3200             True        False
3   3600             True        False
4   4000             True        False
5   2600            False        False
6   2800            False        False
7   3300            False        False
8   3600            False        False
9   2600            False         True
10  2900            False         True
11  3100            False         True
12  3600            False         True

In [11]:
y = df_dummies.price
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [12]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X,y)

LinearRegression()

In [13]:
model.predict([[3000,0,0]])

C:\Users\Mohd Zaid\anaconda3\envs\data-science\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([630482.69189422])

In [14]:
model.predict([[2800,0,1]])

C:\Users\Mohd Zaid\anaconda3\envs\data-science\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([590775.63964739])

In [17]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [18]:
dfle = df

In [19]:
dfle

               town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [22]:
dfle.town = le.fit_transform(dfle.town)

In [23]:
X = dfle[['town','area']].values
X

array([[   0, 2600],
       [   0, 3000],
       [   0, 3200],
       [   0, 3600],
       [   0, 4000],
       [   2, 2600],
       [   2, 2800],
       [   2, 3300],
       [   2, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3600]])

In [24]:
y = dfle.price

In [25]:
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [31]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(
    transformers=[
        ("town", OneHotEncoder(), ["town"])
    ],
    remainder="passthrough"
)

In [38]:
X = ct.fit_transform(dfle)

In [39]:
X

array([[1.00e+00, 0.00e+00, 0.00e+00, 2.60e+03, 5.50e+05],
       [1.00e+00, 0.00e+00, 0.00e+00, 3.00e+03, 5.65e+05],
       [1.00e+00, 0.00e+00, 0.00e+00, 3.20e+03, 6.10e+05],
       [1.00e+00, 0.00e+00, 0.00e+00, 3.60e+03, 6.80e+05],
       [1.00e+00, 0.00e+00, 0.00e+00, 4.00e+03, 7.25e+05],
       [0.00e+00, 0.00e+00, 1.00e+00, 2.60e+03, 5.85e+05],
       [0.00e+00, 0.00e+00, 1.00e+00, 2.80e+03, 6.15e+05],
       [0.00e+00, 0.00e+00, 1.00e+00, 3.30e+03, 6.50e+05],
       [0.00e+00, 0.00e+00, 1.00e+00, 3.60e+03, 7.10e+05],
       [0.00e+00, 1.00e+00, 0.00e+00, 2.60e+03, 5.75e+05],
       [0.00e+00, 1.00e+00, 0.00e+00, 2.90e+03, 6.00e+05],
       [0.00e+00, 1.00e+00, 0.00e+00, 3.10e+03, 6.20e+05],
       [0.00e+00, 1.00e+00, 0.00e+00, 3.60e+03, 6.95e+05]])

In [40]:
X = X[:,1:]
X

array([[0.00e+00, 0.00e+00, 2.60e+03, 5.50e+05],
       [0.00e+00, 0.00e+00, 3.00e+03, 5.65e+05],
       [0.00e+00, 0.00e+00, 3.20e+03, 6.10e+05],
       [0.00e+00, 0.00e+00, 3.60e+03, 6.80e+05],
       [0.00e+00, 0.00e+00, 4.00e+03, 7.25e+05],
       [0.00e+00, 1.00e+00, 2.60e+03, 5.85e+05],
       [0.00e+00, 1.00e+00, 2.80e+03, 6.15e+05],
       [0.00e+00, 1.00e+00, 3.30e+03, 6.50e+05],
       [0.00e+00, 1.00e+00, 3.60e+03, 7.10e+05],
       [1.00e+00, 0.00e+00, 2.60e+03, 5.75e+05],
       [1.00e+00, 0.00e+00, 2.90e+03, 6.00e+05],
       [1.00e+00, 0.00e+00, 3.10e+03, 6.20e+05],
       [1.00e+00, 0.00e+00, 3.60e+03, 6.95e+05]])

In [41]:
model.fit(X,y)

LinearRegression()

In [43]:
model.predict([[1,0,2800]])

ValueError: X has 3 features, but LinearRegression is expecting 4 features as input.